<?php

/*
 * DB connection script for Editor
 * Automatically generated by http://editor.datatables.net/generator
 */

error_reporting(E_ALL);
ini_set('display_errors', '1');

/*
 * Edit the following with your database connection options
 */
$sql_details = array(
	"user" => "U1572520",
	"pass" => "Zqi2f8b9cKDY4n",
	"host" => "rdbms.strato.de",
	"db" => "DB1572520"
);

// PDO connection
$db = new PDO(
	"mysql:host={$sql_details['host']};dbname={$sql_details['db']}",
	$sql_details['user'],
	$sql_details['pass'],
	array(
		PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
	)
);

